/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.37
 * Generated at: 2019-03-21 07:28:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.pages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class editor_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("    <title>Daum 에디터 - 등록화면 예제</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/math/resources/css/editor.css\" type=\"text/css\" charset=\"utf-8\"/>\r\n");
      out.write("    <script src=\"js/editor_loader.js?environment=development\" type=\"text/javascript\" charset=\"utf-8\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"body\">\r\n");
      out.write("\t<!-- 에디터 시작 -->\r\n");
      out.write("\t<!--\r\n");
      out.write("\t\t@decsription\r\n");
      out.write("\t\t등록하기 위한 Form으로 상황에 맞게 수정하여 사용한다. Form 이름은 에디터를 생성할 때 설정값으로 설정한다.\r\n");
      out.write("\t-->\r\n");
      out.write("\t<form name=\"tx_editor_form\" id=\"tx_editor_form\" action=\"http://posttestserver.com/post.php\" method=\"post\" accept-charset=\"utf-8\">\r\n");
      out.write("\t\t<!-- 에디터 컨테이너 시작 -->\r\n");
      out.write("\t\t<div id=\"tx_trex_container\" class=\"tx-editor-container\">\r\n");
      out.write("\t\t\t<!-- 사이드바 -->\r\n");
      out.write("\t\t\t<div id=\"tx_sidebar\" class=\"tx-sidebar\">\r\n");
      out.write("\t\t\t\t<div class=\"tx-sidebar-boundary\">\r\n");
      out.write("\t\t\t\t\t<!-- 사이드바 / 첨부 -->\r\n");
      out.write("\t\t\t\t\t<ul class=\"tx-bar tx-bar-left tx-nav-attach\">\r\n");
      out.write("\t\t\t\t\t\t<!-- 이미지 첨부 버튼 시작 -->\r\n");
      out.write("\t\t\t\t\t\t<!--\r\n");
      out.write("\t\t\t\t\t\t\t@decsription\r\n");
      out.write("\t\t\t\t\t\t\t<li></li> 단위로 위치를 이동할 수 있다.\r\n");
      out.write("\t\t\t\t\t\t-->\r\n");
      out.write("\t\t\t\t\t\t<li class=\"tx-list\">\r\n");
      out.write("\t\t\t\t\t\t\t<div unselectable=\"on\" id=\"tx_image\" class=\"tx-image tx-btn-trans\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"javascript:;\" title=\"사진\" class=\"tx-text\">사진</a>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<!-- 이미지 첨부 버튼 끝 -->\r\n");
      out.write("\t\t\t\t\t\t<li class=\"tx-list\">\r\n");
      out.write("\t\t\t\t\t\t\t<div unselectable=\"on\" id=\"tx_file\" class=\"tx-file tx-btn-trans\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"javascript:;\" title=\"파일\" class=\"tx-text\">파일</a>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"tx-list\">\r\n");
      out.write("\t\t\t\t\t\t\t<div unselectable=\"on\" id=\"tx_media\" class=\"tx-media tx-btn-trans\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"javascript:;\" title=\"외부컨텐츠\" class=\"tx-text\">외부컨텐츠</a>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"tx-list tx-list-extra\">\r\n");
      out.write("\t\t\t\t\t\t\t<div unselectable=\"on\" class=\"tx-btn-nlrbg tx-extra\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"javascript:;\" class=\"tx-icon\" title=\"버튼 더보기\">버튼 더보기</a>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"tx-extra-menu tx-menu\" style=\"left:-48px;\" unselectable=\"on\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<!--\r\n");
      out.write("\t\t\t\t\t\t\t\t\t@decsription\r\n");
      out.write("\t\t\t\t\t\t\t\t\t일부 버튼들을 빼서 레이어로 숨기는 기능을 원할 경우 이 곳으로 이동시킬 수 있다.\r\n");
      out.write("\t\t\t\t\t\t\t\t-->\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t<!-- 사이드바 / 우측영역 -->\r\n");
      out.write("\t\t\t\t\t<ul class=\"tx-bar tx-bar-right\">\r\n");
      out.write("\t\t\t\t\t\t<li class=\"tx-list\">\r\n");
      out.write("\t\t\t\t\t\t\t<div unselectable=\"on\" class=\"tx-btn-lrbg tx-fullscreen\" id=\"tx_fullscreen\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"javascript:;\" class=\"tx-icon\" title=\"넓게쓰기 (Ctrl+M)\">넓게쓰기</a>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t<ul class=\"tx-bar tx-bar-right tx-nav-opt\">\r\n");
      out.write("\t\t\t\t\t\t<li class=\"tx-list\">\r\n");
      out.write("\t\t\t\t\t\t\t<div unselectable=\"on\" class=\"tx-switchtoggle\" id=\"tx_switchertoggle\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"javascript:;\" title=\"에디터 타입\">에디터</a>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- 툴바 - 기본 시작 -->\r\n");
      out.write("\t\t\t<!--\r\n");
      out.write("\t\t\t\t@decsription\r\n");
      out.write("\t\t\t\t툴바 버튼의 그룹핑의 변경이 필요할 때는 위치(왼쪽, 가운데, 오른쪽) 에 따라 <li> 아래의 <div>의 클래스명을 변경하면 된다.\r\n");
      out.write("\t\t\t\ttx-btn-lbg: 왼쪽, tx-btn-bg: 가운데, tx-btn-rbg: 오른쪽, tx-btn-lrbg: 독립적인 그룹\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t드롭다운 버튼의 크기를 변경하고자 할 경우에는 넓이에 따라 <li> 아래의 <div>의 클래스명을 변경하면 된다.\r\n");
      out.write("\t\t\t\ttx-slt-70bg, tx-slt-59bg, tx-slt-42bg, tx-btn-43lrbg, tx-btn-52lrbg, tx-btn-57lrbg, tx-btn-71lrbg\r\n");
      out.write("\t\t\t\ttx-btn-48lbg, tx-btn-48rbg, tx-btn-30lrbg, tx-btn-46lrbg, tx-btn-67lrbg, tx-btn-49lbg, tx-btn-58bg, tx-btn-46bg, tx-btn-49rbg\r\n");
      out.write("\t\t\t-->\r\n");
      out.write("\t\t\t<div id=\"tx_toolbar_basic\" class=\"tx-toolbar tx-toolbar-basic\"><div class=\"tx-toolbar-boundary\">\r\n");
      out.write("\t\t\t\t<ul class=\"tx-bar tx-bar-left\">\r\n");
      out.write("\t\t\t\t\t<li class=\"tx-list\">\r\n");
      out.write("\t\t\t\t\t\t<div id=\"tx_fontfamily\" unselectable=\"on\" class=\"tx-slt-70bg tx-fontfamily\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"javascript:;\" title=\"글꼴\">굴림</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div id=\"tx_fontfamily_menu\" class=\"tx-fontfamily-menu tx-menu\" unselectable=\"on\"></div>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t<ul class=\"tx-bar tx-bar-left\">\r\n");
      out.write("\t\t\t\t\t<li class=\"tx-list\">\r\n");
      out.write("\t\t\t\t\t\t<div unselectable=\"on\" class=\"tx-slt-42bg tx-fontsize\" id=\"tx_fontsize\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"javascript:;\" title=\"글자크기\">9pt</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div id=\"tx_fontsize_menu\" class=\"tx-fontsize-menu tx-menu\" unselectable=\"on\"></div>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t<ul class=\"tx-bar tx-bar-left tx-group-font\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<li class=\"tx-list\">\r\n");
      out.write("\t\t\t\t\t\t<div unselectable=\"on\" class=\"\t\t tx-btn-lbg \ttx-bold\" id=\"tx_bold\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"javascript:;\" class=\"tx-icon\" title=\"굵게 (Ctrl+B)\">굵게</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li class=\"tx-list\">\r\n");
      out.write("\t\t\t\t\t\t<div unselectable=\"on\" class=\"\t\t tx-btn-bg \ttx-underline\" id=\"tx_underline\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"javascript:;\" class=\"tx-icon\" title=\"밑줄 (Ctrl+U)\">밑줄</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li class=\"tx-list\">\r\n");
      out.write("\t\t\t\t\t\t<div unselectable=\"on\" class=\"\t\t tx-btn-bg \ttx-italic\" id=\"tx_italic\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"javascript:;\" class=\"tx-icon\" title=\"기울임 (Ctrl+I)\">기울임</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li class=\"tx-list\">\r\n");
      out.write("\t\t\t\t\t\t<div unselectable=\"on\" class=\"\t\t tx-btn-bg \ttx-strike\" id=\"tx_strike\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"javascript:;\" class=\"tx-icon\" title=\"취소선 (Ctrl+D)\">취소선</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li class=\"tx-list\">\r\n");
      out.write("\t\t\t\t\t\t<div unselectable=\"on\" class=\"\t\t tx-slt-tbg \ttx-forecolor\" id=\"tx_forecolor\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"javascript:;\" class=\"tx-icon\" title=\"글자색\">글자색</a>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"javascript:;\" class=\"tx-arrow\" title=\"글자색 선택\">글자색 선택</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div id=\"tx_forecolor_menu\" class=\"tx-menu tx-forecolor-menu tx-colorpallete\"\r\n");
      out.write("\t\t\t\t\t\t\t unselectable=\"on\"></div>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li class=\"tx-list\">\r\n");
      out.write("\t\t\t\t\t\t<div unselectable=\"on\" class=\"\t\t tx-slt-brbg \ttx-backcolor\" id=\"tx_backcolor\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"javascript:;\" class=\"tx-icon\" title=\"글자 배경색\">글자 배경색</a>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"javascript:;\" class=\"tx-arrow\" title=\"글자 배경색 선택\">글자 배경색 선택</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div id=\"tx_backcolor_menu\" class=\"tx-menu tx-backcolor-menu tx-colorpallete\"\r\n");
      out.write("\t\t\t\t\t\t\t unselectable=\"on\"></div>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t<ul class=\"tx-bar tx-bar-left tx-group-align\">\r\n");
      out.write("\t\t\t\t\t<li class=\"tx-list\">\r\n");
      out.write("\t\t\t\t\t\t<div unselectable=\"on\" class=\"\t\t tx-btn-lbg \ttx-alignleft\" id=\"tx_alignleft\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"javascript:;\" class=\"tx-icon\" title=\"왼쪽정렬 (Ctrl+,)\">왼쪽정렬</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li class=\"tx-list\">\r\n");
      out.write("\t\t\t\t\t\t<div unselectable=\"on\" class=\"\t\t tx-btn-bg \ttx-aligncenter\" id=\"tx_aligncenter\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"javascript:;\" class=\"tx-icon\" title=\"가운데정렬 (Ctrl+.)\">가운데정렬</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li class=\"tx-list\">\r\n");
      out.write("\t\t\t\t\t\t<div unselectable=\"on\" class=\"\t\t tx-btn-bg \ttx-alignright\" id=\"tx_alignright\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"javascript:;\" class=\"tx-icon\" title=\"오른쪽정렬 (Ctrl+/)\">오른쪽정렬</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li class=\"tx-list\">\r\n");
      out.write("\t\t\t\t\t\t<div unselectable=\"on\" class=\"\t\t tx-btn-rbg \ttx-alignfull\" id=\"tx_alignfull\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"javascript:;\" class=\"tx-icon\" title=\"양쪽정렬\">양쪽정렬</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t<ul class=\"tx-bar tx-bar-left tx-group-tab\">\r\n");
      out.write("\t\t\t\t\t<li class=\"tx-list\">\r\n");
      out.write("\t\t\t\t\t\t<div unselectable=\"on\" class=\"\t\t tx-btn-lbg \ttx-indent\" id=\"tx_indent\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"javascript:;\" title=\"들여쓰기 (Tab)\" class=\"tx-icon\">들여쓰기</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li class=\"tx-list\">\r\n");
      out.write("\t\t\t\t\t\t<div unselectable=\"on\" class=\"\t\t tx-btn-rbg \ttx-outdent\" id=\"tx_outdent\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"javascript:;\" title=\"내어쓰기 (Shift+Tab)\" class=\"tx-icon\">내어쓰기</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t<ul class=\"tx-bar tx-bar-left tx-group-list\">\r\n");
      out.write("\t\t\t\t\t<li class=\"tx-list\">\r\n");
      out.write("\t\t\t\t\t\t<div unselectable=\"on\" class=\"tx-slt-31lbg tx-lineheight\" id=\"tx_lineheight\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"javascript:;\" class=\"tx-icon\" title=\"줄간격\">줄간격</a>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"javascript:;\" class=\"tx-arrow\" title=\"줄간격\">줄간격 선택</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div id=\"tx_lineheight_menu\" class=\"tx-lineheight-menu tx-menu\" unselectable=\"on\"></div>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li class=\"tx-list\">\r\n");
      out.write("\t\t\t\t\t\t<div unselectable=\"on\" class=\"tx-slt-31rbg tx-styledlist\" id=\"tx_styledlist\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"javascript:;\" class=\"tx-icon\" title=\"리스트\">리스트</a>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"javascript:;\" class=\"tx-arrow\" title=\"리스트\">리스트 선택</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div id=\"tx_styledlist_menu\" class=\"tx-styledlist-menu tx-menu\" unselectable=\"on\"></div>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t<ul class=\"tx-bar tx-bar-left tx-group-etc\">\r\n");
      out.write("\t\t\t\t\t<li class=\"tx-list\">\r\n");
      out.write("\t\t\t\t\t\t<div unselectable=\"on\" class=\"\t\t tx-btn-lbg \ttx-emoticon\" id=\"tx_emoticon\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"javascript:;\" class=\"tx-icon\" title=\"이모티콘\">이모티콘</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div id=\"tx_emoticon_menu\" class=\"tx-emoticon-menu tx-menu\" unselectable=\"on\"></div>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li class=\"tx-list\">\r\n");
      out.write("\t\t\t\t\t\t<div unselectable=\"on\" class=\"\t\t tx-btn-bg \ttx-link\" id=\"tx_link\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"javascript:;\" class=\"tx-icon\" title=\"링크 (Ctrl+K)\">링크</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div id=\"tx_link_menu\" class=\"tx-link-menu tx-menu\"></div>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li class=\"tx-list\">\r\n");
      out.write("\t\t\t\t\t\t<div unselectable=\"on\" class=\"\t\t tx-btn-bg \ttx-specialchar\" id=\"tx_specialchar\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"javascript:;\" class=\"tx-icon\" title=\"특수문자\">특수문자</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div id=\"tx_specialchar_menu\" class=\"tx-specialchar-menu tx-menu\"></div>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li class=\"tx-list\">\r\n");
      out.write("\t\t\t\t\t\t<div unselectable=\"on\" class=\"\t\t tx-btn-bg \ttx-table\" id=\"tx_table\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"javascript:;\" class=\"tx-icon\" title=\"표만들기\">표만들기</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div id=\"tx_table_menu\" class=\"tx-table-menu tx-menu\" unselectable=\"on\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"tx-menu-inner\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"tx-menu-preview\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"tx-menu-rowcol\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"tx-menu-deco\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"tx-menu-enter\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li class=\"tx-list\">\r\n");
      out.write("\t\t\t\t\t\t<div unselectable=\"on\" class=\"\t\t tx-btn-rbg \ttx-horizontalrule\" id=\"tx_horizontalrule\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"javascript:;\" class=\"tx-icon\" title=\"구분선\">구분선</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div id=\"tx_horizontalrule_menu\" class=\"tx-horizontalrule-menu tx-menu\" unselectable=\"on\"></div>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t<ul class=\"tx-bar tx-bar-left\">\r\n");
      out.write("\t\t\t\t\t<li class=\"tx-list\">\r\n");
      out.write("\t\t\t\t\t\t<div unselectable=\"on\" class=\"\t\t tx-btn-lbg \ttx-richtextbox\" id=\"tx_richtextbox\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"javascript:;\" class=\"tx-icon\" title=\"글상자\">글상자</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div id=\"tx_richtextbox_menu\" class=\"tx-richtextbox-menu tx-menu\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"tx-menu-header\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"tx-menu-preview-area\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"tx-menu-preview\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"tx-menu-switch\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"tx-menu-simple tx-selected\"><a><span>간단 선택</span></a></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"tx-menu-advanced\"><a><span>직접 선택</span></a></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"tx-menu-inner\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"tx-menu-footer\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img class=\"tx-menu-confirm\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t src=\"./images/icon/editor/btn_confirm.gif?rv=1.0.1\" alt=\"\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t<img class=\"tx-menu-cancel\" hspace=\"3\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t src=\"./images/icon/editor/btn_cancel.gif?rv=1.0.1\" alt=\"\"/>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li class=\"tx-list\">\r\n");
      out.write("\t\t\t\t\t\t<div unselectable=\"on\" class=\"\t\t tx-btn-bg \ttx-quote\" id=\"tx_quote\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"javascript:;\" class=\"tx-icon\" title=\"인용구 (Ctrl+Q)\">인용구</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div id=\"tx_quote_menu\" class=\"tx-quote-menu tx-menu\" unselectable=\"on\"></div>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li class=\"tx-list\">\r\n");
      out.write("\t\t\t\t\t\t<div unselectable=\"on\" class=\"\t\t tx-btn-bg \ttx-background\" id=\"tx_background\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"javascript:;\" class=\"tx-icon\" title=\"배경색\">배경색</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div id=\"tx_background_menu\" class=\"tx-menu tx-background-menu tx-colorpallete\"\r\n");
      out.write("\t\t\t\t\t\t\t unselectable=\"on\"></div>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li class=\"tx-list\">\r\n");
      out.write("\t\t\t\t\t\t<div unselectable=\"on\" class=\"\t\t tx-btn-rbg \ttx-dictionary\" id=\"tx_dictionary\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"javascript:;\" class=\"tx-icon\" title=\"사전\">사전</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t<ul class=\"tx-bar tx-bar-left tx-group-undo\">\r\n");
      out.write("\t\t\t\t\t<li class=\"tx-list\">\r\n");
      out.write("\t\t\t\t\t\t<div unselectable=\"on\" class=\"\t\t tx-btn-lbg \ttx-undo\" id=\"tx_undo\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"javascript:;\" class=\"tx-icon\" title=\"실행취소 (Ctrl+Z)\">실행취소</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li class=\"tx-list\">\r\n");
      out.write("\t\t\t\t\t\t<div unselectable=\"on\" class=\"\t\t tx-btn-rbg \ttx-redo\" id=\"tx_redo\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"javascript:;\" class=\"tx-icon\" title=\"다시실행 (Ctrl+Y)\">다시실행</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t<ul class=\"tx-bar tx-bar-right\">\r\n");
      out.write("\t\t\t\t\t<li class=\"tx-list\">\r\n");
      out.write("\t\t\t\t\t\t<div unselectable=\"on\" class=\"tx-btn-nlrbg tx-advanced\" id=\"tx_advanced\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"javascript:;\" class=\"tx-icon\" title=\"툴바 더보기\">툴바 더보기</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div></div>\r\n");
      out.write("\t\t\t<!-- 툴바 - 기본 끝 -->\r\n");
      out.write("\t\t\t<!-- 툴바 - 더보기 시작 -->\r\n");
      out.write("\t\t\t<div id=\"tx_toolbar_advanced\" class=\"tx-toolbar tx-toolbar-advanced\"><div class=\"tx-toolbar-boundary\">\r\n");
      out.write("\t\t\t\t<ul class=\"tx-bar tx-bar-left\">\r\n");
      out.write("\t\t\t\t\t<li class=\"tx-list\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"tx-tableedit-title\"></div>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<ul class=\"tx-bar tx-bar-left tx-group-align\">\r\n");
      out.write("\t\t\t\t\t<li class=\"tx-list\">\r\n");
      out.write("\t\t\t\t\t\t<div unselectable=\"on\" class=\"tx-btn-lbg tx-mergecells\" id=\"tx_mergecells\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"javascript:;\" class=\"tx-icon2\" title=\"병합\">병합</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div id=\"tx_mergecells_menu\" class=\"tx-mergecells-menu tx-menu\" unselectable=\"on\"></div>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li class=\"tx-list\">\r\n");
      out.write("\t\t\t\t\t\t<div unselectable=\"on\" class=\"tx-btn-bg tx-insertcells\" id=\"tx_insertcells\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"javascript:;\" class=\"tx-icon2\" title=\"삽입\">삽입</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div id=\"tx_insertcells_menu\" class=\"tx-insertcells-menu tx-menu\" unselectable=\"on\"></div>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li class=\"tx-list\">\r\n");
      out.write("\t\t\t\t\t\t<div unselectable=\"on\" class=\"tx-btn-rbg tx-deletecells\" id=\"tx_deletecells\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"javascript:;\" class=\"tx-icon2\" title=\"삭제\">삭제</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div id=\"tx_deletecells_menu\" class=\"tx-deletecells-menu tx-menu\" unselectable=\"on\"></div>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<ul class=\"tx-bar tx-bar-left tx-group-align\">\r\n");
      out.write("\t\t\t\t\t<li class=\"tx-list\">\r\n");
      out.write("\t\t\t\t\t\t<div id=\"tx_cellslinepreview\" unselectable=\"on\" class=\"tx-slt-70lbg tx-cellslinepreview\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"javascript:;\" title=\"선 미리보기\"></a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div id=\"tx_cellslinepreview_menu\" class=\"tx-cellslinepreview-menu tx-menu\"\r\n");
      out.write("\t\t\t\t\t\t\t unselectable=\"on\"></div>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li class=\"tx-list\">\r\n");
      out.write("\t\t\t\t\t\t<div id=\"tx_cellslinecolor\" unselectable=\"on\" class=\"tx-slt-tbg tx-cellslinecolor\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"javascript:;\" class=\"tx-icon2\" title=\"선색\">선색</a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"tx-colorpallete\" unselectable=\"on\"></div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div id=\"tx_cellslinecolor_menu\" class=\"tx-cellslinecolor-menu tx-menu tx-colorpallete\"\r\n");
      out.write("\t\t\t\t\t\t\t unselectable=\"on\"></div>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li class=\"tx-list\">\r\n");
      out.write("\t\t\t\t\t\t<div id=\"tx_cellslineheight\" unselectable=\"on\" class=\"tx-btn-bg tx-cellslineheight\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"javascript:;\" class=\"tx-icon2\" title=\"두께\">두께</a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div id=\"tx_cellslineheight_menu\" class=\"tx-cellslineheight-menu tx-menu\"\r\n");
      out.write("\t\t\t\t\t\t\t unselectable=\"on\"></div>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li class=\"tx-list\">\r\n");
      out.write("\t\t\t\t\t\t<div id=\"tx_cellslinestyle\" unselectable=\"on\" class=\"tx-btn-bg tx-cellslinestyle\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"javascript:;\" class=\"tx-icon2\" title=\"스타일\">스타일</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div id=\"tx_cellslinestyle_menu\" class=\"tx-cellslinestyle-menu tx-menu\" unselectable=\"on\"></div>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li class=\"tx-list\">\r\n");
      out.write("\t\t\t\t\t\t<div id=\"tx_cellsoutline\" unselectable=\"on\" class=\"tx-btn-rbg tx-cellsoutline\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"javascript:;\" class=\"tx-icon2\" title=\"테두리\">테두리</a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div id=\"tx_cellsoutline_menu\" class=\"tx-cellsoutline-menu tx-menu\" unselectable=\"on\"></div>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t<ul class=\"tx-bar tx-bar-left\">\r\n");
      out.write("\t\t\t\t\t<li class=\"tx-list\">\r\n");
      out.write("\t\t\t\t\t\t<div id=\"tx_tablebackcolor\" unselectable=\"on\" class=\"tx-btn-lrbg tx-tablebackcolor\"\r\n");
      out.write("\t\t\t\t\t\t\t style=\"background-color:#9aa5ea;\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"javascript:;\" class=\"tx-icon2\" title=\"테이블 배경색\">테이블 배경색</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div id=\"tx_tablebackcolor_menu\" class=\"tx-tablebackcolor-menu tx-menu tx-colorpallete\"\r\n");
      out.write("\t\t\t\t\t\t\t unselectable=\"on\"></div>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t<ul class=\"tx-bar tx-bar-left\">\r\n");
      out.write("\t\t\t\t\t<li class=\"tx-list\">\r\n");
      out.write("\t\t\t\t\t\t<div id=\"tx_tabletemplate\" unselectable=\"on\" class=\"tx-btn-lrbg tx-tabletemplate\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"javascript:;\" class=\"tx-icon2\" title=\"테이블 서식\">테이블 서식</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div id=\"tx_tabletemplate_menu\" class=\"tx-tabletemplate-menu tx-menu tx-colorpallete\"\r\n");
      out.write("\t\t\t\t\t\t\t unselectable=\"on\"></div>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div></div>\r\n");
      out.write("\t\t\t<!-- 툴바 - 더보기 끝 -->\r\n");
      out.write("\t\t\t<!-- 편집영역 시작 -->\r\n");
      out.write("\t\t\t\t<!-- 에디터 Start -->\r\n");
      out.write("\t<div id=\"tx_canvas\" class=\"tx-canvas\">\r\n");
      out.write("\t\t<div id=\"tx_loading\" class=\"tx-loading\"><div><img src=\"/math/resources/images/icon/editor/loading2.png\" width=\"113\" height=\"21\" align=\"absmiddle\"/></div></div>\r\n");
      out.write("\t\t<div id=\"tx_canvas_wysiwyg_holder\" class=\"tx-holder\" style=\"display:block;\">\r\n");
      out.write("\t\t\t<iframe id=\"tx_canvas_wysiwyg\" name=\"tx_canvas_wysiwyg\" allowtransparency=\"true\" frameborder=\"0\"></iframe>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"tx-source-deco\">\r\n");
      out.write("\t\t\t<div id=\"tx_canvas_source_holder\" class=\"tx-holder\">\r\n");
      out.write("\t\t\t\t<textarea id=\"tx_canvas_source\" rows=\"30\" cols=\"30\"></textarea>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"tx_canvas_text_holder\" class=\"tx-holder\">\r\n");
      out.write("\t\t\t<textarea id=\"tx_canvas_text\" rows=\"30\" cols=\"30\"></textarea>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\t\t\t\t<!-- 높이조절 Start -->\r\n");
      out.write("\t<div id=\"tx_resizer\" class=\"tx-resize-bar\">\r\n");
      out.write("\t\t<div class=\"tx-resize-bar-bg\"></div>\r\n");
      out.write("\t\t<img id=\"tx_resize_holder\" src=\"images/icon/editor/skin/01/btn_drag01.gif\" width=\"58\" height=\"12\" unselectable=\"on\" alt=\"\" />\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"tx-side-bi\" id=\"tx_side_bi\">\r\n");
      out.write("\t\t<div style=\"text-align: right;\">\r\n");
      out.write("\t\t\t<img hspace=\"4\" height=\"14\" width=\"78\" align=\"absmiddle\" src=\"images/icon/editor/editor_bi.png\" />\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\t\t\t<!-- 편집영역 끝 -->\r\n");
      out.write("\t\t\t<!-- 첨부박스 시작 -->\r\n");
      out.write("\t\t\t\t<!-- 파일첨부박스 Start -->\r\n");
      out.write("\t<div id=\"tx_attach_div\" class=\"tx-attach-div\">\r\n");
      out.write("\t\t<div id=\"tx_attach_txt\" class=\"tx-attach-txt\">파일 첨부</div>\r\n");
      out.write("\t\t<div id=\"tx_attach_box\" class=\"tx-attach-box\">\r\n");
      out.write("\t\t\t<div class=\"tx-attach-box-inner\">\r\n");
      out.write("\t\t\t\t<div id=\"tx_attach_preview\" class=\"tx-attach-preview\"><p></p><img src=\"images/icon/editor/pn_preview.gif\" width=\"147\" height=\"108\" unselectable=\"on\"/></div>\r\n");
      out.write("\t\t\t\t<div class=\"tx-attach-main\">\r\n");
      out.write("\t\t\t\t\t<div id=\"tx_upload_progress\" class=\"tx-upload-progress\"><div>0%</div><p>파일을 업로드하는 중입니다.</p></div>\r\n");
      out.write("\t\t\t\t\t<ul class=\"tx-attach-top\">\r\n");
      out.write("\t\t\t\t\t\t<li id=\"tx_attach_delete\" class=\"tx-attach-delete\"><a>전체삭제</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li id=\"tx_attach_size\" class=\"tx-attach-size\">\r\n");
      out.write("\t\t\t\t\t\t\t파일: <span id=\"tx_attach_up_size\" class=\"tx-attach-size-up\"></span>/<span id=\"tx_attach_max_size\"></span>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li id=\"tx_attach_tools\" class=\"tx-attach-tools\">\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t<ul id=\"tx_attach_list\" class=\"tx-attach-list\"></ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\t\t\t<!-- 첨부박스 끝 -->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- 에디터 컨테이너 끝 -->\r\n");
      out.write("\t</form>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- 에디터 끝 -->\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tvar config = {\r\n");
      out.write("\t\ttxHost: '', /* 런타임 시 리소스들을 로딩할 때 필요한 부분으로, 경로가 변경되면 이 부분 수정이 필요. ex) http://xxx.xxx.com */\r\n");
      out.write("\t\ttxPath: '', /* 런타임 시 리소스들을 로딩할 때 필요한 부분으로, 경로가 변경되면 이 부분 수정이 필요. ex) /xxx/xxx/ */\r\n");
      out.write("\t\ttxService: 'sample', /* 수정필요없음. */\r\n");
      out.write("\t\ttxProject: 'sample', /* 수정필요없음. 프로젝트가 여러개일 경우만 수정한다. */\r\n");
      out.write("\t\tinitializedId: \"\", /* 대부분의 경우에 빈문자열 */\r\n");
      out.write("\t\twrapper: \"tx_trex_container\", /* 에디터를 둘러싸고 있는 레이어 이름(에디터 컨테이너) */\r\n");
      out.write("\t\tform: 'tx_editor_form'+\"\", /* 등록하기 위한 Form 이름 */\r\n");
      out.write("\t\ttxIconPath: \"images/icon/editor/\", /*에디터에 사용되는 이미지 디렉터리, 필요에 따라 수정한다. */\r\n");
      out.write("\t\ttxDecoPath: \"images/deco/contents/\", /*본문에 사용되는 이미지 디렉터리, 서비스에서 사용할 때는 완성된 컨텐츠로 배포되기 위해 절대경로로 수정한다. */\r\n");
      out.write("\t\tcanvas: {\r\n");
      out.write("            exitEditor:{\r\n");
      out.write("                /*\r\n");
      out.write("                desc:'빠져 나오시려면 shift+b를 누르세요.',\r\n");
      out.write("                hotKey: {\r\n");
      out.write("                    shiftKey:true,\r\n");
      out.write("                    keyCode:66\r\n");
      out.write("                },\r\n");
      out.write("                nextElement: document.getElementsByTagName('button')[0]\r\n");
      out.write("                */\r\n");
      out.write("            },\r\n");
      out.write("\t\t\tstyles: {\r\n");
      out.write("\t\t\t\tcolor: \"#123456\", /* 기본 글자색 */\r\n");
      out.write("\t\t\t\tfontFamily: \"굴림\", /* 기본 글자체 */\r\n");
      out.write("\t\t\t\tfontSize: \"10pt\", /* 기본 글자크기 */\r\n");
      out.write("\t\t\t\tbackgroundColor: \"#fff\", /*기본 배경색 */\r\n");
      out.write("\t\t\t\tlineHeight: \"1.5\", /*기본 줄간격 */\r\n");
      out.write("\t\t\t\tpadding: \"8px\" /* 위지윅 영역의 여백 */\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tshowGuideArea: false\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\tevents: {\r\n");
      out.write("\t\t\tpreventUnload: false\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\tsidebar: {\r\n");
      out.write("\t\t\tattachbox: {\r\n");
      out.write("\t\t\t\tshow: true,\r\n");
      out.write("\t\t\t\tconfirmForDeleteAll: true\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\tsize: {\r\n");
      out.write("\t\t\tcontentWidth: 700 /* 지정된 본문영역의 넓이가 있을 경우에 설정 */\r\n");
      out.write("\t\t}\r\n");
      out.write("\t};\r\n");
      out.write("\r\n");
      out.write("\tEditorJSLoader.ready(function(Editor) {\r\n");
      out.write("\t\tvar editor = new Editor(config);\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<!-- Sample: Saving Contents -->\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t/* 예제용 함수 */\r\n");
      out.write("\tfunction saveContent() {\r\n");
      out.write("\t\tEditor.save(); // 이 함수를 호출하여 글을 등록하면 된다.\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t/**\r\n");
      out.write("\t * Editor.save()를 호출한 경우 데이터가 유효한지 검사하기 위해 부르는 콜백함수로\r\n");
      out.write("\t * 상황에 맞게 수정하여 사용한다.\r\n");
      out.write("\t * 모든 데이터가 유효할 경우에 true를 리턴한다.\r\n");
      out.write("\t * @function\r\n");
      out.write("\t * @param {Object} editor - 에디터에서 넘겨주는 editor 객체\r\n");
      out.write("\t * @returns {Boolean} 모든 데이터가 유효할 경우에 true\r\n");
      out.write("\t */\r\n");
      out.write("\tfunction validForm(editor) {\r\n");
      out.write("\t\t// Place your validation logic here\r\n");
      out.write("\r\n");
      out.write("\t\t// sample : validate that content exists\r\n");
      out.write("\t\tvar validator = new Trex.Validator();\r\n");
      out.write("\t\tvar content = editor.getContent();\r\n");
      out.write("\t\tif (!validator.exists(content)) {\r\n");
      out.write("\t\t\talert('내용을 입력하세요');\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\treturn true;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t/**\r\n");
      out.write("\t * Editor.save()를 호출한 경우 validForm callback 이 수행된 이후\r\n");
      out.write("\t * 실제 form submit을 위해 form 필드를 생성, 변경하기 위해 부르는 콜백함수로\r\n");
      out.write("\t * 각자 상황에 맞게 적절히 응용하여 사용한다.\r\n");
      out.write("\t * @function\r\n");
      out.write("\t * @param {Object} editor - 에디터에서 넘겨주는 editor 객체\r\n");
      out.write("\t * @returns {Boolean} 정상적인 경우에 true\r\n");
      out.write("\t */\r\n");
      out.write("\tfunction setForm(editor) {\r\n");
      out.write("        var i, input;\r\n");
      out.write("        var form = editor.getForm();\r\n");
      out.write("        var content = editor.getContent();\r\n");
      out.write("\r\n");
      out.write("        // 본문 내용을 필드를 생성하여 값을 할당하는 부분\r\n");
      out.write("        var textarea = document.createElement('textarea');\r\n");
      out.write("        textarea.name = 'content';\r\n");
      out.write("        textarea.value = content;\r\n");
      out.write("        form.createField(textarea);\r\n");
      out.write("\r\n");
      out.write("        /* 아래의 코드는 첨부된 데이터를 필드를 생성하여 값을 할당하는 부분으로 상황에 맞게 수정하여 사용한다.\r\n");
      out.write("         첨부된 데이터 중에 주어진 종류(image,file..)에 해당하는 것만 배열로 넘겨준다. */\r\n");
      out.write("        var images = editor.getAttachments('image');\r\n");
      out.write("        for (i = 0; i < images.length; i++) {\r\n");
      out.write("            // existStage는 현재 본문에 존재하는지 여부\r\n");
      out.write("            if (images[i].existStage) {\r\n");
      out.write("                // data는 팝업에서 execAttach 등을 통해 넘긴 데이터\r\n");
      out.write("                alert('attachment information - image[' + i + '] \\r\\n' + JSON.stringify(images[i].data));\r\n");
      out.write("                input = document.createElement('input');\r\n");
      out.write("                input.type = 'hidden';\r\n");
      out.write("                input.name = 'attach_image';\r\n");
      out.write("                input.value = images[i].data.imageurl;  // 예에서는 이미지경로만 받아서 사용\r\n");
      out.write("                form.createField(input);\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        var files = editor.getAttachments('file');\r\n");
      out.write("        for (i = 0; i < files.length; i++) {\r\n");
      out.write("            input = document.createElement('input');\r\n");
      out.write("            input.type = 'hidden';\r\n");
      out.write("            input.name = 'attach_file';\r\n");
      out.write("            input.value = files[i].data.attachurl;\r\n");
      out.write("            form.createField(input);\r\n");
      out.write("        }\r\n");
      out.write("        return true;\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("<div><button onclick='saveContent()'>SAMPLE - submit contents</button></div>\r\n");
      out.write("<!-- End: Saving Contents -->\r\n");
      out.write("\r\n");
      out.write("<!-- Sample: Loading Contents -->\r\n");
      out.write("<textarea id=\"sample_contents_source\" style=\"display:none;\">\r\n");
      out.write("\t<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>\r\n");
      out.write("\t<p style=\"text-align: center;\">\r\n");
      out.write("\t\t<img src=\"http://cfile273.uf.daum.net/image/2064CD374EE1ACCB0F15C8\" class=\"tx-daum-image\" style=\"clear: none; float: none;\"/>\r\n");
      out.write("\t</p>﻿\r\n");
      out.write("\t<p>\r\n");
      out.write("\t\t<a href=\"http://cfile297.uf.daum.net/attach/207C8C1B4AA4F5DC01A644\"><img src=\"snapshot/images/icon/p_gif_s.gif\"/> editor_bi.gif</a>\r\n");
      out.write("\t</p>\r\n");
      out.write("</textarea>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tfunction loadContent() {\r\n");
      out.write("\t\tvar attachments = {};\r\n");
      out.write("\t\tattachments['image'] = [];\r\n");
      out.write("\t\tattachments['image'].push({\r\n");
      out.write("\t\t\t'attacher': 'image',\r\n");
      out.write("\t\t\t'data': {\r\n");
      out.write("\t\t\t\t'imageurl': 'http://cfile273.uf.daum.net/image/2064CD374EE1ACCB0F15C8',\r\n");
      out.write("\t\t\t\t'filename': 'github.gif',\r\n");
      out.write("\t\t\t\t'filesize': 59501,\r\n");
      out.write("\t\t\t\t'originalurl': 'http://cfile273.uf.daum.net/original/2064CD374EE1ACCB0F15C8',\r\n");
      out.write("\t\t\t\t'thumburl': 'http://cfile273.uf.daum.net/P150x100/2064CD374EE1ACCB0F15C8'\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\tattachments['file'] = [];\r\n");
      out.write("\t\tattachments['file'].push({\r\n");
      out.write("\t\t\t'attacher': 'file',\r\n");
      out.write("\t\t\t'data': {\r\n");
      out.write("\t\t\t\t'attachurl': 'http://cfile297.uf.daum.net/attach/207C8C1B4AA4F5DC01A644',\r\n");
      out.write("\t\t\t\t'filemime': 'image/gif',\r\n");
      out.write("\t\t\t\t'filename': 'editor_bi.gif',\r\n");
      out.write("\t\t\t\t'filesize': 640\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t/* 저장된 컨텐츠를 불러오기 위한 함수 호출 */\r\n");
      out.write("\t\tEditor.modify({\r\n");
      out.write("\t\t\t\"attachments\": function () { /* 저장된 첨부가 있을 경우 배열로 넘김, 위의 부분을 수정하고 아래 부분은 수정없이 사용 */\r\n");
      out.write("\t\t\t\tvar allattachments = [];\r\n");
      out.write("\t\t\t\tfor (var i in attachments) {\r\n");
      out.write("\t\t\t\t\tallattachments = allattachments.concat(attachments[i]);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\treturn allattachments;\r\n");
      out.write("\t\t\t}(),\r\n");
      out.write("\t\t\t\"content\": document.getElementById(\"sample_contents_source\") /* 내용 문자열, 주어진 필드(textarea) 엘리먼트 */\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("<div><button onclick='loadContent()'>SAMPLE - load contents to editor</button></div>\r\n");
      out.write("<!-- End: Loading Contents -->\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
