/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.37
 * Generated at: 2019-03-26 11:37:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.main;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/views/main/../common/footer.jsp", Long.valueOf(1552500476847L));
    _jspx_dependants.put("/views/main/../common/header.jsp", Long.valueOf(1553600212082L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write('\r');
      out.write('\n');
 String userId = (String)session.getAttribute("userId"); 
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>감성수학</title>\r\n");
      out.write("<script type=\"text/javascript\" src=\"resources/js/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("<style>\r\n");
      out.write("@import url(https://fonts.googleapis.com/css?family=Raleway:400,500);\r\n");
      out.write(".snip1241 {\r\n");
      out.write("  font-family: 'Raleway', Arial, sans-serif;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  text-transform: uppercase;\r\n");
      out.write("  font-weight: 500;\r\n");
      out.write("  letter-spacing: 1px;\r\n");
      out.write("}\r\n");
      out.write(".snip1241 * {\r\n");
      out.write("  -webkit-box-sizing: border-box;\r\n");
      out.write("  box-sizing: border-box;\r\n");
      out.write("  -webkit-transition: all 0.35s ease;\r\n");
      out.write("  transition: all 0.35s ease;\r\n");
      out.write("}\r\n");
      out.write(".snip1241 li {\r\n");
      out.write("  display: inline-block;\r\n");
      out.write("  list-style: outside none none;\r\n");
      out.write("  margin: 0.5em 1em;\r\n");
      out.write("  padding: 0;\r\n");
      out.write("}\r\n");
      out.write(".snip1241 a {\r\n");
      out.write("  padding: 0.5em 0.8em;\r\n");
      out.write("  color: black;\r\n");
      out.write("  position: relative;\r\n");
      out.write("  text-decoration: none;\r\n");
      out.write("}\r\n");
      out.write(".snip1241 a:before,\r\n");
      out.write(".snip1241 a:after {\r\n");
      out.write("  height: 14px;\r\n");
      out.write("  width: 14px;\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  content: '';\r\n");
      out.write("  -webkit-transition: all 0.35s ease;\r\n");
      out.write("  transition: all 0.35s ease;\r\n");
      out.write("  opacity: 0;\r\n");
      out.write("}\r\n");
      out.write(".snip1241 a:before {\r\n");
      out.write("  right: 0;\r\n");
      out.write("  top: 0;\r\n");
      out.write("  border-right: 3px solid #9b59b6;\r\n");
      out.write("  border-top: 3px solid #9b59b6;\r\n");
      out.write("  -webkit-transform: translate(-100%, 50%);\r\n");
      out.write("  transform: translate(-100%, 50%);\r\n");
      out.write("}\r\n");
      out.write(".snip1241 a:after {\r\n");
      out.write("  left: 0;\r\n");
      out.write("  bottom: 0;\r\n");
      out.write("  border-left: 3px solid #9b59b6;\r\n");
      out.write("  border-bottom: 3px solid #9b59b6;\r\n");
      out.write("  -webkit-transform: translate(100%, -50%);\r\n");
      out.write("  transform: translate(100%, -50%);\r\n");
      out.write("}\r\n");
      out.write(".snip1241 a:hover,\r\n");
      out.write(".snip1241 .current a {\r\n");
      out.write("  color: black;\r\n");
      out.write("}\r\n");
      out.write(".snip1241 a:hover:before,\r\n");
      out.write(".snip1241 .current a:before,\r\n");
      out.write(".snip1241 a:hover:after,\r\n");
      out.write(".snip1241 .current a:after {\r\n");
      out.write("  -webkit-transform: translate(0%, 0%);\r\n");
      out.write("  transform: translate(0%, 0%);\r\n");
      out.write("  opacity: 1;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<ul class=\"snip1241\">\r\n");
      out.write("  <li class=\"current\"><a href=\"#\">감성수학</a></li>\r\n");
      out.write("  <li><a href=\"#\">고객센터관리</a></li>\r\n");
      out.write("  <li><a href=\"#\">FAQ관리</a></li>\r\n");
      out.write("  <li><a href=\"#\">QnA관리</a></li>\r\n");
      out.write("  <li><a href=\"#\">문제관리</a></li>\r\n");
      out.write("  <li><a href=\"/math/myinfo\">마이페이지</a></li>\r\n");
      out.write("  <li><a href=\"/math/logout\">로그아웃</a></li>\r\n");
      out.write("</ul>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<hr style=\"clear:both;\">\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<style>\r\n");
      out.write("</style>\r\n");
      out.write("<title>감성수학</title>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<hr>\r\n");
      out.write("<footer align=\"center\">\r\n");
      out.write("<h1>감성수학</h1> \r\n");
      out.write("</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
